### ISSUE TITLE
Create a TPM plugin

### ISSUE THREAD

**Issue by karismatic-megafauna** [keeganlow/dotfiles#1]
Loved your seamless vim & tmux article! Noticed you had [these](https://github.com/keeganlow/dotfiles/blob/master/.tmux.conf#L52) alterative commands for fzf reasons!

Wondering if you would be interested in creating a TPM plugin for them! 

https://github.com/tmux-plugins/tpm
https://github.com/tmux-plugins/tpm/blob/master/docs/how_to_create_plugin.md

I will if you don't, but I figured you should do it, as it is your idea 👍 

Thanks so much for the article / advice!

**Comment by keeganlow** [comment]
Hey @michaelghinrichs, good idea! I don't use TPM, but if you want to create the plugin, please do. Let me know if you do - I'll add a link in my .tmux.conf for any TPM users who may look at it in the future. 

I'm really glad to hear you enjoyed the article.

Happy hacking!
